# Generated by Django 3.1 on 2020-09-08 21:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
