# Generated by Django 3.1 on 2020-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200908_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
