# Generated by Django 3.1 on 2020-09-09 15:07

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200909_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCreateView',
            fields=[
                ('blogposts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Blog.blogposts')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'Blog.blogposts', django.views.generic.edit.CreateView),
        ),
        migrations.RemoveField(
            model_name='blogposts',
            name='subtitle',
        ),
    ]
